-- Migration: Add slug column to categories table
-- Run this on production via phpMyAdmin or MySQL CLI

ALTER TABLE categories ADD COLUMN slug VARCHAR(100) NULL UNIQUE AFTER name;

UPDATE categories SET slug = CASE id
    WHEN 1  THEN 'restaurant'
    WHEN 2  THEN 'cafe'
    WHEN 3  THEN 'service'
    WHEN 4  THEN 'tourism'
    WHEN 5  THEN 'food'
    WHEN 6  THEN 'beauty'
    WHEN 7  THEN 'market'
    WHEN 8  THEN 'water-dispenser'
    WHEN 9  THEN 'smart-bus-stop'
    WHEN 10 THEN 'motorcycle-taxi'
    WHEN 11 THEN 'gas-station'
    WHEN 12 THEN 'ev-charger'
    WHEN 13 THEN 'lpg-station'
    WHEN 14 THEN 'ngv-station'
    WHEN 15 THEN 'hospital'
    WHEN 16 THEN 'clinic'
    WHEN 17 THEN 'pharmacy'
    WHEN 18 THEN 'temple'
    WHEN 19 THEN 'religious-site'
    WHEN 20 THEN 'tourist-attraction'
    WHEN 21 THEN 'museum'
    WHEN 22 THEN 'shopping-mall'
    WHEN 23 THEN 'fresh-market'
    WHEN 24 THEN 'convenience-store'
    WHEN 25 THEN 'supermarket'
    WHEN 26 THEN 'raan-ahan'
    WHEN 27 THEN 'cafe-coffee'
    WHEN 28 THEN 'bakery'
    WHEN 29 THEN 'shabu-bbq'
    WHEN 30 THEN 'car-care'
    WHEN 31 THEN 'auto-repair'
    WHEN 32 THEN 'car-wash'
    WHEN 33 THEN 'tire-shop'
    WHEN 34 THEN 'school'
    WHEN 35 THEN 'university'
    WHEN 36 THEN 'tutoring'
    WHEN 37 THEN 'hotel'
    WHEN 38 THEN 'park'
    WHEN 39 THEN 'fitness'
    WHEN 40 THEN 'swimming-pool'
    WHEN 41 THEN 'sports'
    WHEN 42 THEN 'bank-atm'
    WHEN 43 THEN 'government'
    WHEN 44 THEN 'post-office'
    WHEN 45 THEN 'other'
    ELSE CONCAT('category-', id)
END;
